In [2]:
import pandas as pd
import numpy as np

In [6]:
dim_date = pd.read_csv("/WINGS-Group-Trade-Marketing-Performance-Analysis/raw_data/dim_date.csv");
dim_product = pd.read_csv("/WINGS-Group-Trade-Marketing-Performance-Analysis/raw_data/dim_product.csv");
dim_outlet = pd.read_csv("/WINGS-Group-Trade-Marketing-Performance-Analysis/raw_data/dim_outlet_raw.csv");

fact_digital_campaign = pd.read_csv("/WINGS-Group-Trade-Marketing-Performance-Analysis/raw_data/fact_digital_campaign.csv");
fact_sales = pd.read_csv("/WINGS-Group-Trade-Marketing-Performance-Analysis/raw_data/fact_sales_raw.csv");
fact_promotion = pd.read_csv("/WINGS-Group-Trade-Marketing-Performance-Analysis/raw_data/fact_promotion.csv")

In [7]:
fact_sales["gross_sales"].head()

0     380000
1     192000
2    1986000
3    1152000
4     938000
Name: gross_sales, dtype: object

In [8]:
fact_sales["gross_sales"] = (
    fact_sales["gross_sales"]
    .astype(str)
    .str.replace(",", "")
)

fact_sales["gross_sales"] = pd.to_numeric(
    fact_sales["gross_sales"],
    errors="coerce"
)

In [9]:
fact_sales["gross_sales"].dtype

dtype('int64')

In [10]:
dim_date["date"] = pd.to_datetime(
    dim_date["date"]
)

In [11]:
dim_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date_id  1461 non-null   int64
 1   date     1461 non-null   datetime64[ns]
 2   month    1461 non-null   int64
 3   quarter  1461 non-null   object
 4   year     1461 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 57.2+ KB

In [12]:
fact_promotion["start_date"] = pd.to_datetime(
    fact_promotion["start_date"]
)

fact_promotion["end_date"] = pd.to_datetime(
    fact_promotion["end_date"]
)

In [13]:
fact_promotion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   promotion_id         80000 non-null  object
 1   sku_id               80000 non-null  object
 2   outlet_id            80000 non-null  object
 3   promo_type           80000 non-null  object
 4   start_date           80000 non-null  datetime64[ns]
 5   end_date             80000 non-null  datetime64[ns]
 6   discount_percentage  79950 non-null  float64
 7   promo_budget         79970 non-null  float64
dtypes: datetime64[ns](2), float64(2), object(4)
memory usage: 4.9+ MB

In [14]:
fact_digital_campaign["start_date"] = pd.to_datetime(
    fact_digital_campaign["start_date"]
)

fact_digital_campaign["end_date"] = pd.to_datetime(
    fact_digital_campaign["end_date"]
)

In [15]:
print("fact_sales")
print(fact_sales.dtypes)

print("\ndim_date")
print(dim_date.dtypes)

print("\nfact_promotion")
print(fact_promotion.dtypes)

print("\nfact_digital_campaign")
print(fact_digital_campaign.dtypes)

fact_sales
transaction_id     object
date_id             int64
outlet_id          object
sku_id             object
quantity          float64
gross_sales         int64
discount          float64
net_sales           int64
dtype: object

dim_date
date_id             int64
date       datetime64[ns]
month               int64
quarter            object
year                int64
dtype: object

fact_promotion
promotion_id                   object
sku_id                         object
outlet_id                      object
promo_type                     object
start_date             datetime64[ns]
end_date               datetime64[ns]
discount_percentage           float64
promo_budget                  float64
dtype: object

fact_digital_campaign
campaign_id                object
sku_id                     object
platform                   object
campaign_type              object
start_date         datetime64[ns]
end_date           datetime64[ns]
spend                       int64
impressions                 int64
clicks                    float64
engagement                  int64
ctr                       float64
conversion_rate           float64
dtype: object

In [16]:
set(fact_promotion["sku_id"]) - set(dim_product["sku_id"])

set()

In [17]:
set(fact_digital_campaign["sku_id"]) - set(dim_product["sku_id"])

set()

In [18]:
fact_digital_campaign.head(5)

,campaign_id,sku_id,platform,campaign_type,start_date,end_date,spend,impressions,clicks,engagement,ctr,conversion_rate
0,CMP000001,SYSTEMA-GEN-001,Facebook,Brand Awareness,2026-03-22,2026-06-07,300310485,8227207,87046.0,627591,1.06,5.74
1,CMP000002,SOKLIN-GEN-001,YouTube,Product Launch,2023-04-01,2023-05-15,458035110,1076449,6184.0,31946,0.57,4.54
2,CMP000003,FROSTBITE-ICE-001,TikTok,Ramadan Campaign,2025-07-28,2025-09-18,702808098,18295201,283355.0,922605,1.55,2.95
3,CMP000004,SEGARDINGIN-GEN-001,YouTube,Promo Campaign,2024-01-08,2024-02-28,458778756,11426912,136514.0,335702,1.19,6.34
4,CMP000005,HERSPROTEX-GEN-001,TikTok,Influencer Campaign,2026-11-25,2026-12-08,390451171,11551238,232100.0,954612,2.01,6.11

In [19]:
fact_promotion["sku_id"].head(10)

0      SYSTEMA-GEN-001
1      EKONOMI-GEN-001
2    ISOPLUS-DRINK-001
3      EKONOMI-GEN-001
4    MIESEDAAP-GEN-001
5     JASJUS-DRINK-001
6      AQUVIVA-GEN-001
7    ALE-ALE-DRINK-001
8    ISOPLUS-DRINK-001
9     JASJUS-DRINK-001
Name: sku_id, dtype: object

In [20]:
fact_promotion["sku_id"] = (
    fact_promotion["sku_id"]
    .str.upper()
)

In [21]:
fact_promotion["sku_id"].head(20)

0       SYSTEMA-GEN-001
1       EKONOMI-GEN-001
2     ISOPLUS-DRINK-001
3       EKONOMI-GEN-001
4     MIESEDAAP-GEN-001
5      JASJUS-DRINK-001
6       AQUVIVA-GEN-001
7     ALE-ALE-DRINK-001
8     ISOPLUS-DRINK-001
9      JASJUS-DRINK-001
10       J-CONE-ICE-001
11      MILKU-DRINK-001
12      MILKU-DRINK-001
13        WINGS-DET-001
14      SOYUMIE-MIE-001
15      EKONOMI-GEN-001
16      EKONOMI-GEN-001
17      MILKU-DRINK-001
18    MIESEDAAP-GEN-001
19       SEDAAP-GEN-002
Name: sku_id, dtype: object

In [22]:
fact_digital_campaign["sku_id"] = (
    fact_digital_campaign["sku_id"]
    .str.upper()
)

In [23]:
missing_sku_promotion = set(
    fact_promotion["sku_id"]
) - set(
    dim_product["sku_id"]
)

missing_sku_promotion

set()

In [24]:
missing_sku_campaign = set(
    fact_digital_campaign["sku_id"]
) - set(
    dim_product["sku_id"]
)

missing_sku_campaign

set()

In [25]:
fact_sales["discount"].isnull().sum()

np.int64(100)

In [26]:
fact_sales["discount"] = fact_sales["discount"].fillna(0)

In [27]:
fact_sales[
    fact_sales["quantity"].isnull()
]

,transaction_id,date_id,outlet_id,sku_id,quantity,gross_sales,discount,net_sales
10502,TRX000010503,20261221,OUT000100,FRESLY-GEN-001,NaN,1053000,52650.0,1000350
12548,TRX000012549,20260507,OUT000810,MAMALEMON-GEN-001,NaN,10766000,322980.0,10443020
22606,TRX000022607,20251220,OUT001130,MIESEDAAP-MIE-002,NaN,15000,150.0,14850
56373,TRX000056374,20261012,OUT000867,JASJUS-DRINK-001,NaN,286000,14300.0,271700
62496,TRX000062497,20241018,OUT000075,MILKU-DRINK-001,NaN,200000,6000.0,194000
97054,TRX000097055,20230919,OUT000814,MAMALEMON-GEN-001,NaN,1610000,32200.0,1577800
130229,TRX000130230,20230522,OUT000833,SOSOFT-DET-001,NaN,3472000,173600.0,3298400
178310,TRX000178311,20250807,OUT000446,CIPTADENT-GEN-001,NaN,372000,11160.0,360840
187434,TRX000187435,20250405,OUT001058,SOKLIN-GEN-001,NaN,75000,3000.0,72000
217336,TRX000217337,20260904,OUT000093,SOKLIN-GEN-001,NaN,540000,16200.0,523800
261005,TRX000261006,20240818,OUT000877,NUVO-SOAP-001,NaN,3288000,131520.0,3156480
263651,TRX000263652,20240816,OUT001031,ISOPLUS-DRINK-001,NaN,1104000,0.0,1104000
280032,TRX000280033,20241231,OUT000662,NEOCOFFEE-COFF-001,NaN,160000,0.0,160000
331812,TRX000331813,20230620,OUT000383,SEGARDINGIN-GEN-001,NaN,468000,9360.0,458640
365668,TRX000365669,20241006,OUT000305,HERSPROTEX-GEN-001,NaN,2560000,76800.0,2483200
465191,TRX000465192,20250921,OUT000405,BOOM-DET-001,NaN,357000,14280.0,342720
481339,TRX000481340,20240718,OUT001179,TOPCOFFEE-COFF-001,NaN,21000,0.0,21000
518712,TRX000518713,20230124,OUT000992,MAMALEMON-GEN-001,NaN,2254000,112700.0,2141300
590422,TRX000590423,20240301,OUT000609,POSH-GEN-001,NaN,444000,8880.0,435120
592844,TRX000592845,20250825,OUT000367,SOKLIN-DET-002,NaN,774000,69660.0,704340
615471,TRX000615472,20260604,OUT000379,SOKLIN-DET-002,NaN,4896000,195840.0,4700160
637147,TRX000637148,20240911,OUT000498,SERASOFT-SHAMP-001,NaN,900000,0.0,900000
686994,TRX000686995,20250318,OUT000978,SEDAAP-GEN-001,NaN,12750000,0.0,12750000
692826,TRX000692827,20241209,OUT000834,TEAJUS-DRINK-001,NaN,343000,6860.0,336140
718248,TRX000718249,20260918,OUT000230,SERASOFT-SHAMP-001,NaN,1020000,20400.0,999600
743529,TRX000743530,20230107,OUT000497,FLORIDINA-DRINK-001,NaN,126000,0.0,126000
747108,TRX000747109,20251116,OUT001101,EKONOMI-DET-001,NaN,20000,200.0,19800
794248,TRX000794249,20230110,OUT000031,WAKUWAKU-ICE-001,NaN,410000,0.0,410000
796626,TRX000796627,20250219,OUT000573,SUPERSOL-GEN-001,NaN,150000,6000.0,144000
808162,TRX000808163,20240727,OUT000897,MIESEDAAP-GEN-001,NaN,1320000,13200.0,1306800
856678,TRX000856679,20260514,OUT000414,HAKU-ICE-001,NaN,520000,15600.0,504400
910368,TRX000910369,20261101,OUT001120,FRESLY-GEN-001,NaN,162000,4860.0,157140
915708,TRX000915709,20250128,OUT000240,WINGS-DET-001,NaN,1280000,0.0,1280000
953562,TRX000953563,20240130,OUT000231,SEDAAP-GEN-001,NaN,2025000,40500.0,1984500
965313,TRX000965314,20230314,OUT000697,POTABEE-GEN-001,NaN,1224000,24480.0,1199520
983169,TRX000983170,20261006,OUT000542,SEDAAP-GEN-002,NaN,327000,3270.0,323730
1040063,TRX001040064,20240506,OUT000647,JASJUS-DRINK-001,NaN,69000,3450.0,65550
1066070,TRX001066071,20260105,OUT001120,SEDAAP-GEN-001,NaN,480000,0.0,480000
1077767,TRX001077768,20230627,OUT000555,WAKUWAKU-ICE-001,NaN,800000,16000.0,784000
1102134,TRX001102135,20240610,OUT000449,SEGARDINGIN-GEN-001,NaN,522000,5220.0,516780
1117536,TRX001117537,20250826,OUT000613,SERASOFT-SHAMP-001,NaN,5760000,230400.0,5529600
1201367,TRX001201368,20230929,OUT000557,EKONOMI-GEN-001,NaN,528000,5280.0,522720
1267176,TRX001267177,20230308,OUT001115,PROGUARD-GEN-001,NaN,36000,1080.0,34920
1280773,TRX001280774,20251022,OUT000153,CIPTADENT-GEN-001,NaN,288000,0.0,288000
1296943,TRX001296944,20250317,OUT000613,TEAJUS-DRINK-001,NaN,67000,2010.0,64990
1308174,TRX001308175,20260102,OUT000676,EKOMIE-MIE-001,NaN,485000,0.0,485000
1309438,TRX001309439,20260203,OUT000729,TEHJAVANA-GEN-001,NaN,864000,25920.0,838080
1341723,TRX001341724,20241230,OUT001116,HERSPROTEX-GEN-001,NaN,60000,600.0,59400
1342527,TRX001342528,20230531,OUT000202,MIESEDAAP-MIE-003,NaN,1152000,0.0,1152000
1405509,TRX001405510,20240306,OUT000626,TEHJAVANA-GEN-001,NaN,612000,6120.0,605880

In [28]:
fact_sales = fact_sales.dropna(
    subset=["quantity"]
)

In [29]:
fact_sales["quantity"].isnull().sum()

np.int64(0)

In [30]:
fact_sales[
    fact_sales["outlet_id"].isnull()
]

,transaction_id,date_id,outlet_id,sku_id,quantity,gross_sales,discount,net_sales
69259,TRX000069260,20260516,NaN,MIESEDAAP-MIE-001,54.0,162000,1620.0,160380
268510,TRX000268511,20250324,NaN,SUPERSOL-GEN-001,223.0,2230000,111500.0,2118500
284373,TRX000284374,20251215,NaN,KODOMO-SHAMP-001,298.0,2384000,23840.0,2360160
385843,TRX000385844,20261203,NaN,CIPTADENT-GEN-001,182.0,1092000,43680.0,1048320
420618,TRX000420619,20260628,NaN,SUPERSOL-GEN-001,38.0,380000,19000.0,361000
425757,TRX000425758,20260725,NaN,SOKLIN-DET-002,62.0,1116000,22320.0,1093680
461544,TRX000461545,20230307,NaN,ISOPLUS-DRINK-001,70.0,280000,14000.0,266000
560950,TRX000560951,20251209,NaN,MIESEDAAP-MIE-001,146.0,438000,17520.0,420480
561573,TRX000561574,20261128,NaN,SOYUMIE-MIE-001,53.0,132500,3975.0,128525
564289,TRX000564290,20261205,NaN,PROGUARD-GEN-001,594.0,7128000,213840.0,6914160
587927,TRX000587928,20250419,NaN,MILKU-DRINK-001,46.0,184000,1840.0,182160
721290,TRX000721291,20250621,NaN,EMERON-SHAMP-001,24.0,360000,3600.0,356400
1012700,TRX001012701,20261004,NaN,HAKU-ICE-001,86.0,860000,17200.0,842800
1041159,TRX001041160,20230108,NaN,DAIA-DET-001,42.0,420000,12600.0,407400
1043498,TRX001043499,20230106,NaN,SYSTEMA-GEN-001,14.0,126000,0.0,126000
1164307,TRX001164308,20240622,NaN,SOKLIN-DET-001,148.0,1776000,35520.0,1740480
1198991,TRX001198992,20250912,NaN,SEGARDINGIN-GEN-001,198.0,594000,5940.0,588060
1239456,TRX001239457,20261012,NaN,JAPOTA-GEN-001,69.0,621000,12420.0,608580
1290921,TRX001290922,20260122,NaN,ZINC-SHAMP-001,4.0,68000,2720.0,65280
1413715,TRX001413716,20250702,NaN,WIZ-GEN-001,28.0,420000,0.0,420000

In [31]:
fact_sales = fact_sales.dropna(
    subset=["outlet_id"]
)

In [32]:
fact_promotion["discount_percentage"] = (
    fact_promotion["discount_percentage"]
    .fillna(0)
)

In [33]:
fact_promotion["promo_budget"] = (
    fact_promotion["promo_budget"]
    .fillna(0)
)

In [34]:
fact_digital_campaign["clicks"] = (
    fact_digital_campaign["clicks"]
    .fillna(0)
)

In [35]:
fact_digital_campaign["ctr"] = (
    fact_digital_campaign["clicks"] /
    fact_digital_campaign["impressions"] * 100
)

In [36]:
fact_digital_campaign["ctr"] = np.where(
    fact_digital_campaign["impressions"] == 0,
    0,
    fact_digital_campaign["clicks"] /
    fact_digital_campaign["impressions"] * 100
)

In [37]:
datasets = {
    "fact_sales": fact_sales,
    "fact_promotion": fact_promotion,
    "fact_digital_campaign": fact_digital_campaign
}


for name, df in datasets.items():
    print("="*40)
    print(name)
    print(df.isnull().sum())

========================================
fact_sales
transaction_id    0
date_id           0
outlet_id         0
sku_id            0
quantity          0
gross_sales       0
discount          0
net_sales         0
dtype: int64
========================================
fact_promotion
promotion_id           0
sku_id                 0
outlet_id              0
promo_type             0
start_date             0
end_date               0
discount_percentage    0
promo_budget           0
dtype: int64
========================================
fact_digital_campaign
campaign_id        0
sku_id             0
platform           0
campaign_type      0
start_date         0
end_date           0
spend              0
impressions        0
clicks             0
engagement         0
ctr                0
conversion_rate    0
dtype: int64

In [38]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\program files\python310\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\program files\python310\lib\site-packages (2.9.13)
Requirement already satisfied: greenlet>=1 in c:\program files\python310\lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\program files\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:22desember2003@localhost:5432/wings_trade_marketing"
)

connection = engine.connect()

print("Database connected successfully!")

connection.close()

Database connected successfully!

In [40]:
dim_product
dim_outlet
dim_date
fact_sales
fact_promotion
fact_digital_campaign

,campaign_id,sku_id,platform,campaign_type,start_date,end_date,spend,impressions,clicks,engagement,ctr,conversion_rate
0,CMP000001,SYSTEMA-GEN-001,Facebook,Brand Awareness,2026-03-22,2026-06-07,300310485,8227207,87046.0,627591,1.058026,5.74
1,CMP000002,SOKLIN-GEN-001,YouTube,Product Launch,2023-04-01,2023-05-15,458035110,1076449,6184.0,31946,0.574481,4.54
2,CMP000003,FROSTBITE-ICE-001,TikTok,Ramadan Campaign,2025-07-28,2025-09-18,702808098,18295201,283355.0,922605,1.548794,2.95
3,CMP000004,SEGARDINGIN-GEN-001,YouTube,Promo Campaign,2024-01-08,2024-02-28,458778756,11426912,136514.0,335702,1.194671,6.34
4,CMP000005,HERSPROTEX-GEN-001,TikTok,Influencer Campaign,2026-11-25,2026-12-08,390451171,11551238,232100.0,954612,2.009308,6.11
...,...,...,...,...,...,...,...,...,...,...,...,...
48839,CMP049996,MIESEDAAP-MIE-001,TikTok,Influencer Campaign,2025-10-03,2025-10-31,448152144,2588174,52845.0,124945,2.041787,6.01
48840,CMP049997,ISOPLUS-DRINK-001,Shopee Ads,12.12 Campaign,2026-05-31,2026-06-14,961216673,6702065,531584.0,567121,7.931645,4.51
48841,CMP049998,TEAJUS-DRINK-001,Shopee Ads,11.11 Campaign,2023-12-08,2024-01-17,465603025,3796597,134964.0,39753,3.554868,1.78
48842,CMP049999,ZINC-SHAMP-001,Instagram,12.12 Campaign,2025-02-16,2025-04-12,125250288,3363092,84476.0,322576,2.511855,6.66
48843,CMP050000,MAMALEMON-GEN-001,Shopee Ads,Product Launch,2026-09-26,2026-11-01,252345093,1912691,79605.0,154878,4.161937,4.05

In [41]:
dim_product.to_sql(
    "dim_product",
    engine,
    schema="trade_marketing",
    if_exists="append",
    index=False
)

58

In [42]:
dim_outlet.to_sql(
    "dim_outlet",
    engine,
    schema="trade_marketing",
    if_exists="append",
    index=False
)

185

In [43]:
dim_date.to_sql(
    "dim_date",
    engine,
    schema="trade_marketing",
    if_exists="append",
    index=False
)

461

In [44]:
fact_sales.to_sql(
    "fact_sales",
    engine,
    schema="trade_marketing",
    if_exists="append",
    index=False,
    chunksize=10000
)

143387

In [45]:
fact_promotion.to_sql(
    "fact_promotion",
    engine,
    schema="trade_marketing",
    if_exists="append",
    index=False
)

1000

In [46]:
fact_digital_campaign.to_sql(
    "fact_digital_campaign",
    engine,
    schema="trade_marketing",
    if_exists="append",
    index=False
)

844

In [47]:
len(fact_sales)

1435387

In [48]:
# SKU yang ada di fact_sales tetapi tidak ada di dim_product

missing_sku_before = set(
    fact_sales["sku_id"]
) - set(
    dim_product["sku_id"]
)

print("Jumlah SKU tidak match:", len(missing_sku_before))

print(list(missing_sku_before)[:20])

Jumlah SKU tidak match: 43
['DAIADET-001', 'EMERONSHAMP-001', 'ZINCSHAMP-001', 'POTABEEGEN-001', 'ALEALE-DRINK-001', 'JCONE-ICE-001', 'TOPCOFFEECOFF-001', 'MILKUDRINK-001', 'WIZGEN-001', 'SOKLINGEN-001', 'HAKUICE-001', 'SEGARDINGINGEN-001', 'EKOMIEMIE-001', 'PROGUARDGEN-001', 'HERSPROTEXGEN-001', 'MAMALEMONGEN-001', 'SEDAAPGEN-001', 'NEOCOFFEECOFF-001', 'EKONOMIDET-002', 'WINGSDET-001']

In [50]:
# Membuat mapping dari dim_product

sku_mapping = {
    sku.replace("-", ""): sku
    for sku in dim_product["sku_id"]
}

In [51]:
list(sku_mapping.items())[:10]

[('SOKLINDET001', 'SOKLIN-DET-001'),
 ('SOKLINDET002', 'SOKLIN-DET-002'),
 ('SOKLINGEN001', 'SOKLIN-GEN-001'),
 ('SOKLINGEN002', 'SOKLIN-GEN-002'),
 ('DAIADET001', 'DAIA-DET-001'),
 ('BOOMDET001', 'BOOM-DET-001'),
 ('EKONOMIDET001', 'EKONOMI-DET-001'),
 ('EKONOMIDET002', 'EKONOMI-DET-002'),
 ('SOSOFTDET001', 'SOSOFT-DET-001'),
 ('WINGSDET001', 'WINGS-DET-001')]

In [52]:
fact_sales["sku_id_clean"] = (
    fact_sales["sku_id"]
    .str.replace("-", "", regex=False)
    .map(sku_mapping)
)

In [53]:
mapped_count = fact_sales["sku_id_clean"].notnull().sum()

print(
    "SKU berhasil dimapping:",
    mapped_count
)

SKU berhasil dimapping: 1435387

In [54]:
unmapped = fact_sales[
    fact_sales["sku_id_clean"].isnull()
]

print(
    "SKU gagal dimapping:",
    len(unmapped)
)

SKU gagal dimapping: 0

In [55]:
unmapped["sku_id"].unique()

array([], dtype=object)

In [56]:
fact_sales["sku_id"] = fact_sales["sku_id_clean"]

In [57]:
fact_sales.drop(
    columns=["sku_id_clean"],
    inplace=True
)

In [58]:
missing_sku_after = set(
    fact_sales["sku_id"]
) - set(
    dim_product["sku_id"]
)

print(
    "Jumlah SKU tidak match setelah cleaning:",
    len(missing_sku_after)
)

Jumlah SKU tidak match setelah cleaning: 0

In [60]:
fact_sales.to_csv(
    "raw_data/fact_sales_clean.csv",
    index=False
)

In [61]:
fact_sales.to_sql(
    name="fact_sales",
    con=engine,
    schema="trade_marketing",
    if_exists="append",
    index=False,
    chunksize=10000
)

143387

In [63]:
len(fact_sales)

1435387

In [64]:
# Check duplicate transaction_id

duplicate_before = fact_sales[
    fact_sales["transaction_id"].duplicated()
]

print("Jumlah duplicate:", len(duplicate_before))

Jumlah duplicate: 68

In [65]:
# Remove duplicate berdasarkan transaction_id

fact_sales_clean = fact_sales.drop_duplicates(
    subset=["transaction_id"],
    keep="first"
)

In [66]:
duplicate_after = fact_sales_clean[
    fact_sales_clean["transaction_id"].duplicated()
]

print("Duplicate setelah cleaning:", len(duplicate_after))

Duplicate setelah cleaning: 0

In [67]:
print("Jumlah data sebelum:", len(fact_sales))
print("Jumlah data sesudah:", len(fact_sales_clean))
print("Data yang dihapus:", len(fact_sales)-len(fact_sales_clean))

Jumlah data sebelum: 1435387
Jumlah data sesudah: 1435319
Data yang dihapus: 68

In [68]:
fact_sales = fact_sales_clean.copy()

In [69]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(
        text(
            "TRUNCATE TABLE trade_marketing.fact_sales;"
        )
    )

In [70]:
fact_sales.to_sql(
    name="fact_sales",
    con=engine,
    schema="trade_marketing",
    if_exists="append",
    index=False,
    chunksize=10000
)

143319

In [71]:
pd.read_sql(
    """
    SELECT COUNT(*) 
    FROM trade_marketing.fact_sales;
    """,
    engine
)

     count
0  1435319

In [72]:
len(fact_sales)

1435319

In [73]:
pd.read_sql(
    """
    SELECT 
        transaction_id,
        COUNT(*) AS total
    FROM trade_marketing.fact_sales
    GROUP BY transaction_id
    HAVING COUNT(*) > 1;
    """,
    engine
)

Empty DataFrame
Columns: [transaction_id, total]
Index: []